//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public int ID { get; set; }
        public int PEDIDO_SERVICIO { get; set; }
        public int ESTADO_VAL { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual VALOR VALOR { get; set; }
        public virtual PEDIDO_SERVICIO PEDIDO_SERVICIO1 { get; set; }
    }
}
