//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.PEDIDO_SERVICIO = new HashSet<PEDIDO_SERVICIO>();
        }
    
        public int ID { get; set; }
        public int USUARIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DIRECCION { get; set; }
        public string COMENTARIO { get; set; }
        public int ESTADO_VAL { get; set; }
        public string LATITUD { get; set; }
        public string LONGITUD { get; set; }
    
        public virtual VALOR VALOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_SERVICIO> PEDIDO_SERVICIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
